# Caching Go modules for future builds
# FROM golang:alpine3.21 as modules
# COPY go.mod /modules/
# WORKDIR /modules
# RUN go mod download

# Building app
FROM golang:alpine3.21 as builder
# COPY --from=modules /go/pkg /go/pkg
# COPY . /app
CMD ["/bin/sh"]
EXPOSE 3001